stages:
- build_image
- test
- deploy

variables:
   MYSQL_DATABASE: jasmine
   MYSQL_ROOT_PASSWORD: newpass
   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip/"
   IMAGE: fjl2401/${CI_PROJECT_NAME}
before_script:
- IMAGE_TAG=${IMAGE}:${CI_COMMIT_SHA:0:8}

cache:
  key: ${CI_JOB_NAME}
  paths:
  - ${PIP_CACHE_DIR}


build_image:
  stage: build_image
  tags:
  - docker
  script:
  - docker build ${IMAGE_TAG} -f Dockerfile .
  - docker push ${IMAGE_TAG}

test:
  image: $IMAGE_TAG
  stage: test
  services:
  - name: mysql:5.6
    alias: mysql
  - name: redis:4
    alias: redis
  before_script:
  - python -V
  script:
  - flake8 app db jobs tests
  - pytest -s -x

