stages:
- build_image
- test
- deploy

variables:
   MYSQL_DATABASE: jasmine
   MYSQL_ROOT_PASSWORD: newpass
   PIP_CACHE_DIR: "/root/.cache/pip/"
   IMAGE: fjl2401/${CI_PROJECT_NAME}
before_script:
- IMAGE_TAG=${IMAGE}:${CI_COMMIT_SHA:0:8}

cache:
  key: ${CI_JOB_NAME}
  paths:
  - ${PIP_CACHE_DIR}


build_image:
  stage: build_image
  tags:
  - build_image
  script:
  - docker build -t ${IMAGE_TAG} -f Dockerfile .
  - docker login -u "$REGISTRY_USERNAME" --password "$REGISTRY_PASSWORD"
  - docker push ${IMAGE_TAG}

test:
  image: $IMAGE_TAG
  stage: test
  services:
  - name: mysql:5.6
    alias: mysql
  - name: redis:4
    alias: redis
  before_script:
  - python -V
  script:
  - flake8 app db jobs tests
  - pytest -s -x

deploy:
  stage: deploy
#  连接到 ssh服务器 然后 将image替换为新的image 然后docker-compose 重新启动
  script:
  - ssh ubuntu@111.231.82.45

