stages:
- test
- build
- deploy

variables:
   MYSQL_DATABASE: jasmine
   MYSQL_ROOT_PASSWORD: newpass


test:
  image: "docker.io/fjl2401/jasmine:latest"
  stage: test
  services:
  - name: mysql:5.6
    alias: mysql
  - name: redis:4
    alias: redis
  before_script:
  - python -V
  script:
  - pip install flake8 && pip install pytest
  - flake8 app db jobs tests
  - pytest -s -x

