version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 8000:80
    depends_on:
      - jasmine
  mysql:
    image: mysql:5.7
    volumes:
      - /data/mysql/jasmine/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newpass
      MYSQL_DATABASE: jasmine
#    env_file:
#      - env/mysql.env
  redis:
    image: redis:4.0
    volumes:
      - /data/redis/data:/data
    restart: always
  jasmine:
    depends_on:
      - mysql
      - redis
    build: .
    image: jasmine:latest
    ports:
      - 5000:5000
    restart: always
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
      FLASK_ENV: production
    command: bash -c "flask user create_user && ../boot.sh run"
  celery:
    depends_on:
      - redis
      - mysql
    image: jasmine:latest
    restart: always
    environment:
      REDIS_HOST: redis
    command: ../boot.sh run_celery
volumes:
  redis:
