version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 8000:80
    depends_on:
      - jasmine
  db:
    image: mysql:5.7
    volumes:
      - /data/mysql/jasmine/data:/var/lib/mysql
    restart: always
    env_file:
      - env/mysql.env
  redis:
    image: redis:4.0
    volumes:
      - /data/redis/data:/data
    restart: always
  jasmine:
    depends_on:
      - db
      - redis
    build: .
    restart: always
    environment:
      DB_HOST: db
      REDIS_HOST: redis